// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />
import "dotenv/config";
import { defineConfig } from "prisma/config";

// fix lỗi prisma khi deploy
function databaseUrl() {
  const url = process.env.DATABASE_URL ?? "";
  if (!url) return url;

  const queryIndex = url.indexOf("?");
  const base = queryIndex === -1 ? url : url.slice(0, queryIndex);
  const params = new URLSearchParams(
    queryIndex === -1 ? "" : url.slice(queryIndex + 1),
  );

  params.delete("ssl");
  if (!params.has("sslaccept")) {
    params.set("sslaccept", "strict");
  }

  const query = params.toString();
  return query ? `${base}?${query}` : base;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl(),
  },
});
